"use client"

import { useEffect, useMemo, useState } from "react"
import { morphSupabaseQuery } from "@/lib/morph/supabase-public"

const TOKEN_KEY = "morph_owner_access"
type Payment = { id: string; project_id: string | null; provider: string; kind: string; amount_cents: number; currency: string; status: string; verified_at: string | null; created_at: string; provider_payment_status: string | null; provider_checkout_url: string | null }

function money(cents:number,currency:string){return new Intl.NumberFormat("en",{style:"currency",currency:currency||"EUR",maximumFractionDigits:0}).format(cents/100)}

export default function FinancePage(){
  const [payments,setPayments]=useState<Payment[]>([])
  const [loading,setLoading]=useState(true)
  const [error,setError]=useState("")
  useEffect(()=>{const token=sessionStorage.getItem(TOKEN_KEY);if(!token){queueMicrotask(()=>setLoading(false));return}morphSupabaseQuery<Payment>("morph_payments",token,{select:"id,project_id,provider,kind,amount_cents,currency,status,verified_at,created_at,provider_payment_status,provider_checkout_url",order:"created_at.desc",limit:100}).then(setPayments).catch(()=>setError("Live payment data is unavailable.")).finally(()=>setLoading(false))},[])
  const totals=useMemo(()=>payments.reduce((acc,p)=>{const isSettled=/paid|finished|confirmed|verified/i.test(`${p.status} ${p.provider_payment_status||""}`);if(isSettled)acc.received+=Number(p.amount_cents||0);else acc.pending+=Number(p.amount_cents||0);return acc},{received:0,pending:0}),[payments])
  const currency=payments[0]?.currency||"EUR"
  return <>
    <header className="border-b border-black/10 pb-8"><p className="text-[10px] uppercase tracking-[0.2em] text-black/35">Finance</p><h1 className="mt-3 text-[clamp(2.5rem,5vw,5.5rem)] font-semibold leading-[0.9] tracking-[-0.065em]">What is paid.<br/>What is still locked.</h1><p className="mt-5 max-w-2xl text-sm leading-6 text-black/45">Live MORPH payment registry. Deposits and balances stay tied to project delivery gates.</p></header>
    <section className="grid border-b border-black/10 sm:grid-cols-3"><article className="py-6 sm:p-6"><p className="text-[9px] uppercase tracking-[0.16em] text-black/35">Received</p><p className="mt-4 text-4xl font-semibold tracking-[-0.055em]">{loading?"—":money(totals.received,currency)}</p><p className="mt-2 text-xs text-black/40">Verified / settled records</p></article><article className="py-6 sm:border-l sm:border-black/10 sm:p-6"><p className="text-[9px] uppercase tracking-[0.16em] text-black/35">Pending</p><p className="mt-4 text-4xl font-semibold tracking-[-0.055em]">{loading?"—":money(totals.pending,currency)}</p><p className="mt-2 text-xs text-black/40">Not yet settled</p></article><article className="py-6 sm:border-l sm:border-black/10 sm:p-6"><p className="text-[9px] uppercase tracking-[0.16em] text-black/35">Payment records</p><p className="mt-4 text-4xl font-semibold tracking-[-0.055em]">{loading?"—":String(payments.length).padStart(2,"0")}</p><p className="mt-2 text-xs text-black/40">Latest 100 records</p></article></section>
    <section className="py-7">{error&&<p role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}{!loading&&payments.length===0?<div className="rounded-2xl border border-black/10 bg-white p-8"><p className="text-[10px] uppercase tracking-[0.16em] text-black/35">Live finance</p><h2 className="mt-3 text-2xl font-semibold tracking-[-0.04em]">No payment records yet.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-black/45">The provider integration will create and verify deposits and balances here. No fake revenue is displayed.</p></div>:<div className="overflow-hidden rounded-2xl border border-black/10 bg-white">{payments.map((payment,index)=><article key={payment.id} className={`grid gap-4 p-5 lg:grid-cols-[1fr_0.7fr_0.7fr_0.9fr] lg:items-center ${index>0?"border-t border-black/10":""}`}><div><h2 className="font-semibold tracking-[-0.025em]">{payment.kind||"Payment"}</h2><p className="mt-1 text-xs text-black/40">Project {payment.project_id||"—"}</p></div><p className="text-sm font-semibold">{money(Number(payment.amount_cents||0),payment.currency||currency)}</p><div><p className="text-[9px] uppercase tracking-[0.13em] text-black/35">{payment.provider}</p><p className="mt-2 text-xs font-medium">{payment.provider_payment_status||payment.status}</p></div><div className="lg:text-right"><p className="text-xs text-black/45">{payment.verified_at?`Verified ${new Date(payment.verified_at).toLocaleString()}`:`Created ${new Date(payment.created_at).toLocaleString()}`}</p>{payment.provider_checkout_url&&<a href={payment.provider_checkout_url} target="_blank" rel="noreferrer" className="mt-2 inline-block text-[10px] font-semibold text-[#5548d9]">Open checkout →</a>}</div></article>)}</div>}</section>
  </>
}
